language: php
php:
  - 7.1
  - 7.2
  - master

env:
  - dependencies=lowest
  - dependencies=highest

matrix:
  allow_failures:
    - php: master
    - stage: phar

before_script:
  - if php --ri xdebug >/dev/null; then phpenv config-rm xdebug.ini; fi

install:
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --no-interaction; fi
  - if [ "$dependencies" = "highest" ]; then composer update --no-interaction; fi

jobs:
  include:
    - script: vendor/bin/phing
    - stage: phar
      #if: env(TRAVIS_PHP_VERSION) = "7.1" && env(dependencies) = "highest" && branch = master
      script:
        - echo $TRAVIS_PHP_VERSION
        - echo $dependencies
      #  - git clone https://github.com/phpstan/phpstan-compiler && cd phpstan-compiler && ./run-e2e-tests.sh $TRAVIS_COMMIT
      #after_success:
      #  - commit generated phar to phpstan-shim
#

cache:
  directories:
    - $HOME/.composer/cache
    - tmp
